[package]
name = "A4_Krocket"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3"